import React, { useMemo, useState } from 'react'
import Papa from 'papaparse'
import Charts from './components/Charts'
import JobsTable from './components/Table'
import { parsePdfFile } from './utils/pdfParser'

function formatShare(count, total) {
  if (!total) return '0%'
  return `${Math.round((count / total) * 100)}%`
}

export default function App() {
  const [jobs, setJobs] = useState([])
  const [fileName, setFileName] = useState('No file chosen')
  const [error, setError] = useState(null)

  const normalizeJob = (job, index) => ({
    id: index,
    ...job,
    is_remote: String(job.is_remote).toLowerCase() === 'true',
  })

  function handleFile(e) {
    const file = e.target.files[0]
    if (!file) return
    setFileName(file.name)
    const isPdf = file.type === 'application/pdf' || file.name.toLowerCase().endsWith('.pdf')
    if (isPdf) {
      setError(null)
      setJobs([])
      parsePdfFile(file)
        .then(data => {
          if (!data || data.length === 0) {
            setError('We could not detect a clean table in the PDF. Try a PDF with selectable text or a CSV export.')
            return
          }
          setJobs(data.map((r, i) => normalizeJob(r, i)))
        })
        .catch(err => setError(String(err)))
    } else {
      Papa.parse(file, {
        header: true,
        skipEmptyLines: true,
        complete: (results) => {
          setJobs(results.data.map((r, i) => normalizeJob(r, i)))
          setError(null)
        },
        error: (err) => setError(err.message),
      })
    }
  }

  const metrics = useMemo(() => {
    const total = jobs.length
    const companies = new Set(jobs.map((job) => job.company).filter(Boolean)).size
    const remote = jobs.filter((job) => job.is_remote).length
    const onsite = total - remote
    const dated = jobs.filter((job) => job.date_posted).length
    const topSource =
      jobs.reduce((acc, job) => {
        const key = job.site || 'Unknown'
        acc[key] = (acc[key] || 0) + 1
        return acc
      }, {})

    const winner = Object.entries(topSource).sort((a, b) => b[1] - a[1])[0]

    return {
      total,
      companies,
      remote,
      onsite,
      dated,
      winner: winner ? winner[0] : '—',
    }
  }, [jobs])

  const heroChips = ['CSV / PDF intake', 'Source-aware cards', 'Remote vs onsite at a glance']

  const quickSignals = [
    { label: 'Listings loaded', value: metrics.total },
    { label: 'Unique companies', value: metrics.companies },
    { label: 'Rows with dates', value: metrics.dated },
    { label: 'Top source', value: metrics.winner },
  ]

  return (
    <main className="app-shell">
      <div className="page-orbit page-orbit-left" />
      <div className="page-orbit page-orbit-right" />
      <header className="page-header">
        <div className="brand-lockup">
          <span className="brand-mark">AI/ML</span>
          <div>
            <p className="brand-title">Internship Intelligence</p>
            <p className="brand-subtitle">A calmer, cleaner way to read job data.</p>
          </div>
        </div>
        <div className="status-chip">Live dashboard shell</div>
      </header>

      <section className="hero card">
        <div className="hero-copy">
          <p className="eyebrow">AI/ML Internship Intelligence</p>
          <h1>Data that looks editorial, not autogenerated.</h1>
          <p className="subtitle">
            Drop in a CSV exported by the scraper or a searchable PDF, then scan the listings through a more human-feeling dashboard with stronger rhythm, better hierarchy, and cleaner signals.
          </p>
          <div className="hero-chips">
            {heroChips.map((chip) => (
              <span key={chip} className="hero-chip">{chip}</span>
            ))}
          </div>
        </div>

        <div className="hero-panel">
          <div className="hero-panel-top">
            <span className="pill">CSV / PDF ready</span>
            <span className="file-name">{fileName}</span>
          </div>

          <div className="hero-note">
            Upload a CSV export from the scraper or a searchable PDF. The dashboard will turn the raw feed into a more polished board with source colors, work-mode chips, and easier scanning.
          </div>

          <label className="dropzone" htmlFor="job-upload">
            <span className="dropzone-title">Drop CSV or PDF here</span>
            <span className="dropzone-subtitle">or click to browse and load the board</span>
            <input id="job-upload" type="file" accept=".csv,.pdf,text/csv,application/pdf" onChange={handleFile} />
          </label>

          {error && <div className="error-banner">{error}</div>}

          <div className="signal-grid">
            {quickSignals.map((signal) => (
              <div className="signal-card" key={signal.label}>
                <span>{signal.label}</span>
                <strong>{signal.value}</strong>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="stats-grid">
        <article className="stat-card card">
          <span className="stat-label">Listings</span>
          <strong>{metrics.total}</strong>
          <small>Jobs loaded from the current file</small>
        </article>
        <article className="stat-card card">
          <span className="stat-label">Companies</span>
          <strong>{metrics.companies}</strong>
          <small>Unique employers found</small>
        </article>
        <article className="stat-card card">
          <span className="stat-label">Remote Share</span>
          <strong>{formatShare(metrics.remote, metrics.total)}</strong>
          <small>{metrics.remote} remote jobs found</small>
        </article>
        <article className="stat-card card">
          <span className="stat-label">On-site / Hybrid</span>
          <strong>{metrics.onsite}</strong>
          <small>Jobs that need local presence</small>
        </article>
        <article className="stat-card card">
          <span className="stat-label">Top Source</span>
          <strong>{metrics.winner}</strong>
          <small>Source with the most listings</small>
        </article>
      </section>

      {jobs.length > 0 ? (
        <>
          <Charts jobs={jobs} />
          <JobsTable jobs={jobs} />
        </>
      ) : (
        <section className="empty-state card">
          <div className="empty-badge">Ready when you are</div>
          <h2>No data loaded yet.</h2>
          <p>Upload <strong>ai_internships_lahore.csv</strong> or a job listings PDF to reveal charts, tables, and source breakdowns.</p>
        </section>
      )}
    </main>
  )
}
